package ventanas;

import conexiones.accesoCategorias;
import conexiones.accesoProductos;
import java.awt.Image;
import java.io.File;
import java.io.InputStream;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.AbstractDocument;
import fieldFormats.DecimalDocumentFilter;
import fieldFormats.RangoDocumentFilter;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import objetos.Categoria;
import objetos.Empleado;
import objetos.Producto;

public class FormularioProducto extends javax.swing.JFrame {

    private Empleado usuario;
    private Producto producto = null;
    private InputStream fotoProducto = null;
    private boolean fotoSubida = false;
    
    private accesoProductos productos;
    private accesoCategorias categorias;
    private ArrayList<Categoria> categoriasData;   
    
    private Double precioBASE = 0.0;
    private Double IVA = 0.0;
    private Double descuento = 0.0;
    private Double precioFINAL = 0.0;
    
    public FormularioProducto() {
        config();
    }

    public FormularioProducto(Empleado usuario) {
        config();
        
        this.usuario = usuario;
        
        lblUltimaModificacion.setVisible(false);
    }
    
    public FormularioProducto(Empleado usuario, Producto producto) {
        config();
        
        this.usuario = usuario;
        this.producto = producto;    
        
        txtCodigoBarras.setText(producto.getCodigoBarras());
        txtClave.setText(producto.getClave());
        txtDescripcion.setText(producto.getDescripcion());
        txtMarca.setText(producto.getMarca());
        cmbCategorias.setSelectedItem(producto.getIdCategoria());
        txtPrecio.setText("" + producto.getPrecio());
        txtDescuento.setText("" + producto.getDescuento());
        txtStock.setText("" + producto.getStock());
        int id = producto.getIdCategoria();
        String cat = categorias.getNombre(id);
        cmbCategorias.setSelectedItem(cat);
        if (producto.getFotoLeida() != null)
            lblFoto.setIcon(new ImageIcon(producto.getFotoLeida().getScaledInstance(256, 256, Image.SCALE_SMOOTH)));
        lblUltimaModificacion.setText("Última Modificación: " + producto.getUltimaModificacion());

        calcularPrecios();
    }
    
    private void config () {
        initComponents();        
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        
        ((AbstractDocument) txtPrecio.getDocument()).setDocumentFilter(new DecimalDocumentFilter(10, 2));
        ((AbstractDocument) txtDescuento.getDocument()).setDocumentFilter(new RangoDocumentFilter(0, 100));
        ((AbstractDocument) txtStock.getDocument()).setDocumentFilter(new RangoDocumentFilter(0, 1000000));
        
        rbtConIVA.setSelected(true);
        
        productos = new accesoProductos();
        categorias = new accesoCategorias();
        categoriasData = categorias.getTodasLasCategorias();
        for (Categoria c : categoriasData)
            cmbCategorias.addItem(c.getNombre());
    }
    
    private void calcularPrecios () {
        if (!txtPrecio.getText().equals("") && !txtDescuento.getText().equals("")) {
            Double precio = Double.parseDouble(txtPrecio.getText());

            if (rbtConIVA.isSelected()) {
                precioBASE = precio/(1.16);
                precioFINAL = precio;
                IVA = precioFINAL - precioBASE;
            }
            else {
                precioBASE = precio;
                IVA = precio*0.16;
                precioFINAL = precioBASE+IVA;
            }
            
            descuento = precioFINAL*(Double.parseDouble(txtDescuento.getText()))/100.0;
            
            lblPrecioBase.setText(String.format("%.2f", precioBASE));
            lblIVA.setText(String.format("%.2f", IVA));
            lblDescuento.setText(String.format("%.2f", descuento));
            lblPrecioFinal.setText(String.format("%.2f", precioFINAL-descuento));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodigoBarras = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        btnSubir = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        txtClave = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        cmbCategorias = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        txtDescuento = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rbtConIVA = new javax.swing.JRadioButton();
        rbtSinIVA = new javax.swing.JRadioButton();
        lblPrecioBase = new javax.swing.JLabel();
        lblIVA = new javax.swing.JLabel();
        lblDescuento = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        lblPrecioFinal = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        addCategory = new javax.swing.JButton();
        lblUltimaModificacion = new javax.swing.JLabel();
        lblPrecioBase1 = new javax.swing.JLabel();
        lblIVA1 = new javax.swing.JLabel();
        lblDescuento1 = new javax.swing.JLabel();
        lblPrecioFinal1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 173, 29));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("AGREGAR/MODIFICAR PRODUCTO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Código de Barras:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("* Clave:");

        txtCodigoBarras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("* Descripción:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("* Marca:");

        lblFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NoAvailable.jpg"))); // NOI18N

        btnSubir.setBackground(new java.awt.Color(102, 255, 102));
        btnSubir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSubir.setText("SUBIR");
        btnSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirActionPerformed(evt);
            }
        });

        btnQuitar.setBackground(new java.awt.Color(102, 255, 102));
        btnQuitar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuitar.setText("QUITAR");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        txtClave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtMarca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cmbCategorias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Categoria:");

        txtPrecio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPrecio.setText("0.00");
        txtPrecio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrecioFocusLost(evt);
            }
        });
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrecioKeyReleased(evt);
            }
        });

        txtDescuento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDescuento.setText("0");
        txtDescuento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescuentoFocusLost(evt);
            }
        });
        txtDescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescuentoKeyReleased(evt);
            }
        });

        txtStock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtStock.setText("0");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Precio: $");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Descuento: %");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Stock:");

        buttonGroup1.add(rbtConIVA);
        rbtConIVA.setText("IVA Incluido");
        rbtConIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtConIVAActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtSinIVA);
        rbtSinIVA.setText("Sin IVA");
        rbtSinIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtSinIVAActionPerformed(evt);
            }
        });

        lblPrecioBase.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrecioBase.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPrecioBase.setText("0.00");

        lblIVA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIVA.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIVA.setText("0.00");

        lblDescuento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDescuento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDescuento.setText("0.00");

        btnGuardar.setBackground(new java.awt.Color(102, 255, 102));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblPrecioFinal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrecioFinal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPrecioFinal.setText("0.00");

        txtDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnCancelar.setBackground(new java.awt.Color(102, 255, 102));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        addCategory.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addCategory.setText("+");
        addCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCategoryActionPerformed(evt);
            }
        });

        lblUltimaModificacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUltimaModificacion.setText("Última Modificacion:");

        lblPrecioBase1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrecioBase1.setText("Precio BASE: $");

        lblIVA1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblIVA1.setText("IVA: $");

        lblDescuento1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDescuento1.setText("Descuento: $");

        lblPrecioFinal1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPrecioFinal1.setText("Precio FINAL: $");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMarca)
                                            .addComponent(txtClave)
                                            .addComponent(txtDescripcion)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(cmbCategorias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(addCategory))
                                                    .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(30, 30, 30))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(rbtSinIVA)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtStock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                                .addComponent(txtDescuento, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtPrecio, javax.swing.GroupLayout.Alignment.LEADING)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPrecioBase, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblIVA, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDescuento, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblPrecioBase1)
                                            .addComponent(lblIVA1)
                                            .addComponent(lblDescuento1)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(rbtConIVA)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblPrecioFinal1)))
                                        .addGap(169, 169, 169)
                                        .addComponent(lblPrecioFinal))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(352, 352, 352)
                                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblUltimaModificacion)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUltimaModificacion)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addComponent(addCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(lblPrecioBase)
                    .addComponent(lblPrecioBase1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(lblIVA)
                    .addComponent(lblIVA1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(lblDescuento)
                    .addComponent(lblDescuento1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrecioFinal)
                    .addComponent(lblPrecioFinal1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtConIVA)
                        .addComponent(rbtSinIVA)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        Inventario i = new Inventario(usuario);
        i.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String clave = txtClave.getText().toUpperCase();
        String descripcion = txtDescripcion.getText();
        String marca = txtMarca.getText();
        
        String errorMessage = "FALTA INGRESAR:";
        if (clave.equals(""))
            errorMessage += "\n - Clave";
        if (descripcion.equals(""))
            errorMessage += "\n - Descripción";
        if (marca.equals(""))
            errorMessage += "\n - Marca";
        
        if (errorMessage.equals("FALTA INGRESAR:")) {
            Producto nuevo = new Producto();
            if (producto != null)
                nuevo.setId(producto.getId());
            nuevo.setCodigoBarras(txtCodigoBarras.getText());
            nuevo.setClave(clave);
            nuevo.setDescripcion(descripcion);
            nuevo.setMarca(marca);
            nuevo.setPrecio(Double.parseDouble(txtPrecio.getText()));
            nuevo.setDescuento(Integer.parseInt(txtDescuento.getText()));
            nuevo.setStock(Integer.parseInt(txtStock.getText()));
            int idCategoria = categorias.getId("" + cmbCategorias.getSelectedItem());
            nuevo.setIdCategoria(idCategoria);
            nuevo.setFoto(fotoProducto);

            boolean ok = productos.guardarProducto(nuevo);
            if (ok) {
                JOptionPane.showMessageDialog(this, "El producto se ha guardado", "", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                Inventario i = new Inventario(usuario);
                i.setVisible(true);
            }
            else
                JOptionPane.showMessageDialog(this, "El producto no se pudo guardar", "¡ERROR!", JOptionPane.ERROR_MESSAGE);
            
        }
        else
            JOptionPane.showMessageDialog(this, errorMessage, "", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirActionPerformed
        JFileChooser archivoSelector = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de imagen", "jpg", "png");
        archivoSelector.setFileFilter(filtro);
        
        int resultado = archivoSelector.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File selectedFile = archivoSelector.getSelectedFile();
            ImageIcon imagenIcono = new ImageIcon(selectedFile.getAbsolutePath());
            Image imagen = imagenIcono.getImage();
            Image imagenRedimensionada = imagen.getScaledInstance(256, 256, Image.SCALE_SMOOTH);
            lblFoto.setIcon(new ImageIcon(imagenRedimensionada));
            
            try {
                fotoProducto = new FileInputStream (selectedFile);
                fotoSubida = true;
            } catch (FileNotFoundException ex) {
                Logger.getLogger(FormularioProducto.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSubirActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        ImageIcon imagenIcono = new ImageIcon("C:\\Users\\EliteBook\\Documents\\NetBeansProjects\\Proyecto_BD\\src\\images\\NoAvailable.jpg");
        Image imagen = imagenIcono.getImage();   
        lblFoto.setIcon(new ImageIcon(imagen));
        fotoProducto = producto.getFoto();
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void addCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCategoryActionPerformed
        try {
            String nombre = JOptionPane.showInputDialog("Escribe el nombre de la nueva categoria a añadir: ").toUpperCase();

            boolean repetida = false;
            for (Categoria c : categoriasData){
                if (c.getNombre().equals(nombre)) {
                    repetida = true;
                    break;
                }
            }
            
            if (!repetida) {
                Categoria nueva = new Categoria();
                nueva.setNombre(nombre);
                boolean ok = categorias.agregarCategoria(nueva);

                if (ok) {
                    JOptionPane.showMessageDialog(this, "Categoria añadida", "", JOptionPane.INFORMATION_MESSAGE);
                    categoriasData = categorias.getTodasLasCategorias();
                    cmbCategorias.removeAllItems();
                    for (Categoria c : categoriasData)
                        cmbCategorias.addItem(c.getNombre());
                }
                else
                    JOptionPane.showMessageDialog(this, "No se pudo añadir la categoria", "¡ERROR!", JOptionPane.ERROR_MESSAGE);
            }
            else
                JOptionPane.showMessageDialog(this, "Ya existe una categoria con ese nombre", "¡ERROR!", JOptionPane.ERROR_MESSAGE);
        }
        catch (Exception e) {}
    }//GEN-LAST:event_addCategoryActionPerformed

    private void rbtConIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtConIVAActionPerformed
        calcularPrecios();
    }//GEN-LAST:event_rbtConIVAActionPerformed

    private void rbtSinIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtSinIVAActionPerformed
        calcularPrecios();
    }//GEN-LAST:event_rbtSinIVAActionPerformed

    private void txtPrecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyReleased
        calcularPrecios();
    }//GEN-LAST:event_txtPrecioKeyReleased

    private void txtDescuentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescuentoKeyReleased
        calcularPrecios();
    }//GEN-LAST:event_txtDescuentoKeyReleased

    private void txtPrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecioFocusLost
        String s = txtPrecio.getText();
        if(s.equals(""))
            txtPrecio.setText("0.00");
        else 
            txtPrecio.setText(String.format("%.2f", Double.parseDouble(s)));
        
        calcularPrecios();
    }//GEN-LAST:event_txtPrecioFocusLost

    private void txtDescuentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescuentoFocusLost
        if(txtDescuento.getText().equals(""))
            txtDescuento.setText("0");
        
        calcularPrecios();
    }//GEN-LAST:event_txtDescuentoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCategory;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JButton btnSubir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbCategorias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JLabel lblDescuento1;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblIVA1;
    private javax.swing.JLabel lblPrecioBase;
    private javax.swing.JLabel lblPrecioBase1;
    private javax.swing.JLabel lblPrecioFinal;
    private javax.swing.JLabel lblPrecioFinal1;
    private javax.swing.JLabel lblUltimaModificacion;
    private javax.swing.JRadioButton rbtConIVA;
    private javax.swing.JRadioButton rbtSinIVA;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtCodigoBarras;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
