package ventanas;

import conexiones.accesoEmpleados;
import conexiones.accesoProductos;
import conexiones.accesoVentas;
import java.util.ArrayList;
import javax.swing.JFrame;
import objetos.DetalleVenta;
import objetos.Empleado;
import objetos.Venta;

public class ticket extends javax.swing.JFrame {

    private Empleado usuario;
    
    private accesoVentas ventas;
    private accesoEmpleados empleados;
    private accesoProductos productos;
    
    public ticket () {
        config();
    }
    
    public ticket(Empleado usuario, int idVenta) {
        config();
        
        this.usuario = usuario;
        
        Venta v = ventas.getVenta(idVenta);
        ArrayList<DetalleVenta> detalles = ventas.getTodosLosDetalles(idVenta);
        
        String s = "\t\t\t\tPARAISO RANGEL - YURIRIA\n"
                + "\t\t     Hidalgo #1000, Yuriria Centro, 38940 Yuriria, Gto.\n\n"
                + "TicketID:\t" + v.getId() + "\n"
                + "Atendió:\t\t" + usuario.getNombre() + "\n"
                + "Fecha:\t\t" + v.getFecha() +"\n\n"
                + "----------------------------------------------------------------------------------------\n"
                + "#Cant.\tClave\tDescripcion\t\t\t Precio Unitario\t Importe\n"
                + "----------------------------------------------------------------------------------------\n";
        
        for (DetalleVenta dv : detalles) {
            String des = productos.getDescripcionProducto(dv.getIdProducto());
            s += (dv.getCantidad() + "\t");
            s += (dv.getIdProducto() + "\t");
            s += (des);
            for (int i=des.length(); i<28; i++)
                s += " ";
            String pre = String.format("%.2f",(dv.getPrecio()-dv.getDescuento()));
            for (int i=pre.length(); i<20; i++)
                s += " ";
            s += ("$ " + pre);
            String imp = String.format("%.2f",((dv.getCantidad()*dv.getPrecio())-(dv.getDescuento()*dv.getCantidad())));
            for (int i=imp.length(); i<20; i++)
                s += " ";
            s += ("$ " + imp);
            s += "\n";
        }
        
        
                s += "----------------------------------------------------------------------------------------\n"
                + "\t\t\t\t\t\t\t\tSubTotal:  $\t" + String.format("%.2f", v.getSubTotal()) + "\n"
                + "\t\t\t\t\t\t\t\tIVA (16%): $\t" + String.format("%.2f", v.getIva()) + "\n"
                + "\t\t\t\t\t\t\t\tDescuento: $\t" + String.format("%.2f", v.getDescuento()) + "\n\n"
                + "\t\t\t\t\t\t\t\tTOTAL:     $\t" + String.format("%.2f", v.getTotal()) + "\n\n\n"
                + "\t\t\t\tGRACIAS POR SU COMPRA :D";
        txtInfo.setText(s);
    }
    
    private void config () {
        initComponents();
        
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        
        ventas = new accesoVentas();
        productos = new accesoProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInfo = new javax.swing.JTextArea();
        btnOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 173, 29));

        txtInfo.setEditable(false);
        txtInfo.setColumns(20);
        txtInfo.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        txtInfo.setRows(5);
        txtInfo.setToolTipText("");
        jScrollPane1.setViewportView(txtInfo);

        btnOk.setBackground(new java.awt.Color(102, 255, 102));
        btnOk.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(290, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtInfo;
    // End of variables declaration//GEN-END:variables
}
